### ISSUE TITLE
USDT or USDC?

### ISSUE THREAD

**Issue by NikitaBerezhnoy** [Maxim280596/yo-smart-contracts#11]
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L39

**Comment by NikitaBerezhnoy** [comment]
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L585-L590

**Comment by NikitaBerezhnoy** [comment]
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L136

**Comment by Maxim280596** [comment]
Corrected
