### ISSUE TITLE
can be replaced to ; i < array.length;

### ISSUE THREAD

**Issue by NikitaBerezhnoy** [Maxim280596/yo-smart-contracts#12]
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L350
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L696
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L709
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L733
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L736
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L756
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L762
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L791
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L833
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L851
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L865
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L897
https://github.com/Maxim280596/yo-smart-contracts/blob/a2f693d30faaabe396396318337b5887cddc0847/contracts/YieldOptimizer.sol#L1023

**Comment by Maxim280596** [comment]
Corrected
