### ISSUE TITLE
Comments starting with  //// 

### ISSUE THREAD

**Issue by NikitaBerezhnoy** [Maxim280596/yo-smart-contracts#19]
https://github.com/Maxim280596/yo-smart-contracts/blob/5a579fecec1b4bea9285a86255bdd6f309bb4632/contracts/YieldOptimizer.sol#L70
Please change "////" to "//". These comments can rendered as strikethrough text.
![image](https://user-images.githubusercontent.com/61778877/208437590-8b0b634d-e1cd-4d04-9545-e410305d67e2.png)

**Comment by Maxim280596** [comment]
Done
