### ISSUE TITLE
Pause and recover

### ISSUE THREAD

**Issue by NikitaBerezhnoy** [Maxim280596/yo-smart-contracts#21]
- The contract does not include any function to freeze or pause the contract in the event of an emergency or security issue. This could make it difficult to mitigate the impact of any vulnerabilities or attacks that may occur.
- The contract does not include any function to allow for the recovery of funds in the event of an emergency or security issue. This could make it difficult to recover from any loss of funds due to vulnerabilities or attacks.

**Comment by Maxim280596** [comment]
I will try to add this functionality, but currently the contract already has a maximum size.

**Comment by Maxim280596** [comment]
Added Pausable and EmergencyWithdraw functionality. I had to sacrifice some view methods, but the data they return can be obtained from pool contracts and Beethoven X vault. Also removed some null address checks.
